set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR arm64)
set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "" FORCE)
set(CMAKE_OSX_DEPLOYMENT_TARGET "16.0" CACHE STRING "" FORCE)
set(CMAKE_OSX_SYSROOT "iphoneos" CACHE STRING "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(PKG_CONFIG_EXECUTABLE "" CACHE FILEPATH "" FORCE)
# CMAKE_FIND_ROOT_PATH and CMAKE_PREFIX_PATH must be passed via -D on CLI
# or set in the project's CMakeLists.txt. CMAKE_SOURCE_DIR varies per sub-project.
# Use: -DCMAKE_FIND_ROOT_PATH=<path> -DCMAKE_PREFIX_PATH=<path>
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
